### ISSUE TITLE
Possible to look up translation keys partially with a variable?

### ISSUE THREAD

**Issue by StefanWallin** [Anthony-Gaudino/jekyll-multiple-languages-plugin#37]
I'm trying to implement a change languages menu with languages set in the current language, but having a difficult time getting the translation key to lookup the word for the language in the current language.

The troublesome line looks like this:

``` liquid
  {% t languages[language] %}
```

Here, _t_ matches the translate keyword, _languages_ is part of the keyname as a plain string and _language_ is a variable containing the current language as a string. Is it not possible to do this kind of lookup with liquid and jekyll-multiple-languages-plugin? I've scoured the manuals of both liquid and this plugin and the above way seem to be how liquid handles it, but it doesn't work with this framework. What am I doing wrong? Or is this not an intended feature or a bug?

**_config.yml**

``` yaml
...
languages: ["en", "sv"]
exclude_from_localizations: ["javascript", "images", "css"]
...
```

**en.yml**

``` yaml
languages:
    sv: Swedish
    en: English
```

**langmenu.html**

``` liquid
{% for language in site.languages %}
    {% if forloop.first %}
        <a href="/">
            {% t languages[language] %}
        </a>
    {% else %}
        <a href="/{{ language }}">
            {% t languages[language] %}
        </a>
    {% endif %}
{% endfor %}
```
