### ISSUE TITLE
Is it possible to translate objects in front matter?

### ISSUE THREAD

**Issue by pklada** [Anthony-Gaudino/jekyll-multiple-languages-plugin#67]
```
subnav:
  - name: subtitle.overview
    hash: overview
  - name: subtitle.examples
    hash: examples
  - name: subtitle.builder
    hash: builder
  - name: subtitle.resources
    hash: resources
```

This is something we're trying to do (define the navigation in the front matter) but the 'name' keys here aren't being translated (just shows up as a literal string).
