### ISSUE TITLE
Permalinks of custom collection documents are not translated.

### ISSUE THREAD

**Issue by klaasnotfound** [Anthony-Gaudino/jekyll-multiple-languages-plugin#87]
I am using this plugin for a site with custom collections. In addition to the `_posts` folder I have an `_faq` folder that contains a collection of frequently asked questions. For SEO purposes each of these questions should end up with its own translated URL.

In my `_config.yml` I added
``` yaml
collections:
  faq:
    output: true
```
and the collection documents are rendered into each language folder. However, the permalinks are always in the default language. I.e. for a site with languages `["de", "en"]` (German being the default), _all_ rendered versions of the question

``` yaml
layout: faq
title: faq.how-much

namespace: faq.how-much
permalink: /faq/wieviel-kostet-es
permalink_en: /faq/how-much-does-it-cost
```
end up having the URL `<lang>/faq/wieviel-kostet-es` (including the English version).

I looked at the source code of the plugin and realized the permalink translation is missing for documents. Simply copying [the permalink translation code](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin/blob/master/lib/jekyll-multiple-languages-plugin.rb#L188-L201) to the [document code](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin/blob/master/lib/jekyll-multiple-languages-plugin.rb#L263) actually fixed the problem, i.e. all links are translated correctly.

Maybe you could double-check whether this is the right way to do it and include this fix in the next release.
